export enum GenerationProviderType {
  OPENAI = "OPENAI",
  GOOGLE = "GOOGLE",
  ANTHROPIC = "ANTHROPIC",
  RUNWAY = "RUNWAY",
  KLING = "KLING",
  PIKA = "PIKA",
  ELEVENLABS = "ELEVENLABS",
  STABILITY = "STABILITY",
  CUSTOM = "CUSTOM",
}
