export enum GenerationState {
  CREATED = "CREATED",
  INITIALIZED = "INITIALIZED",
  QUEUED = "QUEUED",
  WAITING = "WAITING",
  GENERATING = "GENERATING",
  VALIDATING = "VALIDATING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}
