export enum AssetType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  VOICE = "VOICE",
  MUSIC = "MUSIC",
  SFX = "SFX",
  BACKGROUND = "BACKGROUND",
  TRANSITION = "TRANSITION",
  TEXT = "TEXT",
  SUBTITLE = "SUBTITLE",
}
