export enum ProductionState {
  CREATED = "CREATED",
  INITIALIZED = "INITIALIZED",
  RUNNING = "RUNNING",
  PLANNING = "PLANNING",
  READY = "READY",
  GENERATING = "GENERATING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  STOPPED = "STOPPED",
}
