export enum WorkspaceState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  ARCHIVED = "ARCHIVED",
  BACKING_UP = "BACKING_UP",
  RESTORING = "RESTORING",
  FAILED = "FAILED",
}
