import { ModelDescriptor } from "@shaily/core";

export const OpenAIModels: readonly ModelDescriptor[] = [
  {
    id: "gpt-4o",
    providerId: "openai",
    capabilities: {
      chat: true,
      vision: true,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 4096,
    costMetadata: { inputCostPer1K: 0.005, outputCostPer1K: 0.015 },
    latencyMetadata: { averageLatencyMs: 300 },
    enabled: true,
    displayName: "GPT-4o (OpenAI)",
    vision: true,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "gpt-4o-mini",
    providerId: "openai",
    capabilities: {
      chat: true,
      vision: true,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 16384,
    costMetadata: { inputCostPer1K: 0.00015, outputCostPer1K: 0.0006 },
    latencyMetadata: { averageLatencyMs: 100 },
    enabled: true,
    displayName: "GPT-4o Mini (OpenAI)",
    vision: true,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "text-embedding-3-small",
    providerId: "openai",
    capabilities: {
      chat: false,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: false,
      jsonMode: false,
      streaming: false,
    },
    contextWindow: 8191,
    maxOutput: 0,
    costMetadata: { inputCostPer1K: 0.00002, outputCostPer1K: 0 },
    latencyMetadata: { averageLatencyMs: 50 },
    enabled: true,
    displayName: "Text Embedding 3 Small (OpenAI)",
    vision: false,
    tools: false,
    streaming: false,
    embeddings: true,
    JSON: false,
  },
];
