export enum DashboardEventType {
  REFRESH = "REFRESH",
  COMMAND_EXECUTED = "COMMAND_EXECUTED",
  WIDGET_UPDATED = "WIDGET_UPDATED",
  STATE_CHANGED = "STATE_CHANGED",
  NOTIFICATION_ADDED = "NOTIFICATION_ADDED",
  ERROR_OCCURRED = "ERROR_OCCURRED"
}
