export enum DashboardSection {
  OVERVIEW = "OVERVIEW",
  DAILY_WORK = "DAILY_WORK",
  PROVIDERS = "PROVIDERS",
  CONTENT_PRODUCTION = "CONTENT_PRODUCTION",
  ANALYTICS = "ANALYTICS",
  IMPROVEMENT = "IMPROVEMENT",
  MONITORING = "MONITORING",
  SETTINGS = "SETTINGS",
  COMMAND_CENTER = "COMMAND_CENTER",
  NOTIFICATIONS = "NOTIFICATIONS"
}
