export enum ExecutionEventType {
  REQUEST_STARTED    = "REQUEST_STARTED",
  REQUEST_COMPLETED  = "REQUEST_COMPLETED",
  CACHE_HIT          = "CACHE_HIT",
  CACHE_MISS         = "CACHE_MISS",
  BUDGET_ALERT       = "BUDGET_ALERT",
  PROVIDER_SELECTED  = "PROVIDER_SELECTED",
  QUALITY_SCORED     = "QUALITY_SCORED"
}
