export enum SelectionStrategy {
  COST_OPTIMIZED      = "COST_OPTIMIZED",
  SPEED_OPTIMIZED     = "SPEED_OPTIMIZED",
  QUALITY_OPTIMIZED   = "QUALITY_OPTIMIZED",
  BALANCED            = "BALANCED",
  FOUNDER_PREFERRED   = "FOUNDER_PREFERRED",
  AVAILABILITY_FIRST  = "AVAILABILITY_FIRST"
}
