export enum KnowledgeBaseState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  INDEXING = "INDEXING",
  SEARCHING = "SEARCHING",
  PAUSED = "PAUSED",
  STOPPING = "STOPPING",
  STOPPED = "STOPPED",
  FAILED = "FAILED",
}
