export enum RelationshipType {
  PARENT = "PARENT",
  CHILD = "CHILD",
  RELATED = "RELATED",
  DEPENDS_ON = "DEPENDS_ON",
  GENERATED_BY = "GENERATED_BY",
  REFERENCES = "REFERENCES",
  INSPIRED_BY = "INSPIRED_BY",
  DUPLICATE_OF = "DUPLICATE_OF",
  PRECEDES = "PRECEDES",
  FOLLOWS = "FOLLOWS",
  CONTRADICTS = "CONTRADICTS",
  SUPPORTS = "SUPPORTS",
}
