export enum ObservabilityEventType {
  LOG_EMITTED = "LOG_EMITTED",
  METRIC_COLLECTED = "METRIC_COLLECTED",
  TRACE_COMPLETED = "TRACE_COMPLETED",
  ALERT_TRIGGERED = "ALERT_TRIGGERED",
  BACKUP_COMPLETED = "BACKUP_COMPLETED",
  ARCHIVE_CREATED = "ARCHIVE_CREATED"
}
