export enum PerformanceEventType {
  PROFILE_COMPLETED = "PROFILE_COMPLETED",
  CACHE_HIT = "CACHE_HIT",
  CACHE_MISS = "CACHE_MISS",
  HEAP_COMPACTED = "HEAP_COMPACTED",
  OPTIMIZATION_TRIGGERED = "OPTIMIZATION_TRIGGERED",
  THRESHOLD_EXCEEDED = "THRESHOLD_EXCEEDED"
}
