export enum KnowledgeSource {
  RESEARCH_ENGINE = "RESEARCH_ENGINE",
  SCRIPT_ENGINE = "SCRIPT_ENGINE",
  PIPELINE_ENGINE = "PIPELINE_ENGINE",
  ASSISTANT_ENGINE = "ASSISTANT_ENGINE",
  WORKSPACE_ENGINE = "WORKSPACE_ENGINE",
  ANALYTICS_ENGINE = "ANALYTICS_ENGINE",
  LEARNING_ENGINE = "LEARNING_ENGINE",
  OPTIMIZATION_ENGINE = "OPTIMIZATION_ENGINE",
  FOUNDER_ENGINE = "FOUNDER_ENGINE",
  MANUAL = "MANUAL",
  IMPORTED = "IMPORTED",
  GENERATED = "GENERATED",
}
