import { ILogger } from "../logger/ILogger";
import { IConfig } from "../config/IConfig";
import { IServiceRegistry } from "../registry/IServiceRegistry";
import { IEventBus } from "../events/IEventBus";
import { IAIEngine } from "../ai/IAIEngine";
import { IPlanningEngine } from "../planning/IPlanningEngine";
import { IConversationManager } from "../conversation/IConversationManager";
import { IWorkflowEngine } from "../workflow/IWorkflowEngine";
import { IAgentRegistry } from "../agents/IAgentRegistry";
import { IResearchEngine } from "../research/interfaces";
import { IStrategyEngine } from "../strategy/interfaces";
import { IChannelEngine } from "../channel/interfaces";
import { IScriptEngine } from "../script/interfaces";
import { IAssetEngine } from "../assets/interfaces";
import { IProductionEngine } from "../production/interfaces";
import { IGenerationEngine } from "../generation/interfaces";
import { ICompositionEngine } from "../video-composition/interfaces";
import { IRenderEngine } from "../rendering/interfaces";
import { IQualityEngine } from "../quality/interfaces";
import { IRuntimeEngine } from "../runtime/interfaces";
import { IWorkspaceEngine } from "../workspace/interfaces";
import { IAssistantEngine } from "../assistant/interfaces";
import { ITaskSchedulerEngine } from "../task-scheduler/interfaces";
import { ISettingsEngine } from "../settings/interfaces";
import { ISystemIntegrationEngine } from "../system-integration/interfaces";
import { IStabilityPerformanceEngine } from "../stability-performance/interfaces";
import { IConfigurationEngine } from "../configuration/interfaces";
import { IObservabilityEngine } from "../observability/interfaces";
import { IGatewayEngine } from "../ai-gateway/interfaces";
import { IProviderExecutionEngine } from "../provider-execution/interfaces";
import { IDatabaseEngine } from "../database/interfaces";
import { ILLMProviderEngine } from "../llm-provider/interfaces";
import { IMediaProviderEngine } from "../media-provider/interfaces";
import { IContentPipelineEngine } from "../content-pipeline/interfaces";
import { IYouTubeIntegrationEngine } from "../youtube-integration/interfaces";
import { ISocialPlatformEngine } from "../social-platform/interfaces";
import { IAnalyticsEngine } from "../analytics/interfaces";
import { IAutonomousImprovementEngine } from "../autonomous-improvement/interfaces";
import { IDashboardEngine } from "../dashboard/interfaces";
import { IPerformanceEngine } from "../performance/interfaces";
import { IDailyAutomationEngine } from "../daily-automation/interfaces";
import { IFounderAIEngine } from "../founder-ai/interfaces";

export interface MemoryContext {
  readonly logger: ILogger;
  readonly runtimeEngine?: IRuntimeEngine;
  readonly workspaceEngine?: IWorkspaceEngine;
  readonly assistantEngine?: IAssistantEngine;
  readonly schedulerEngine?: ITaskSchedulerEngine;
  readonly settingsEngine?: ISettingsEngine;
  readonly systemIntegrationEngine?: ISystemIntegrationEngine;
  readonly stabilityPerformanceEngine?: IStabilityPerformanceEngine;
  readonly configurationEngine?: IConfigurationEngine;
  readonly observabilityEngine?: IObservabilityEngine;
  readonly gatewayEngine?: IGatewayEngine;
  readonly providerExecutionEngine?: IProviderExecutionEngine;
  readonly databaseEngine?: IDatabaseEngine;
  readonly llmProviderEngine?: ILLMProviderEngine;
  readonly mediaProviderEngine?: IMediaProviderEngine;
  readonly contentPipelineEngine?: IContentPipelineEngine;
  readonly youtubeIntegrationEngine?: IYouTubeIntegrationEngine;
  readonly socialPlatformEngine?: ISocialPlatformEngine;
  readonly analyticsEngine?: IAnalyticsEngine;
  readonly autonomousImprovementEngine?: IAutonomousImprovementEngine;
  readonly dashboardEngine?: IDashboardEngine;
  readonly performanceEngine?: IPerformanceEngine;
  readonly dailyAutomationEngine?: IDailyAutomationEngine;
  readonly founderAIEngine?: IFounderAIEngine;
  readonly config: IConfig;
  readonly registry: IServiceRegistry;
  readonly eventBus: IEventBus;

  readonly aiEngine?: IAIEngine;
  readonly planningEngine?: IPlanningEngine;
  readonly conversationManager?: IConversationManager;
  readonly workflowEngine?: IWorkflowEngine;
  readonly agentRegistry?: IAgentRegistry;
  readonly researchEngine?: IResearchEngine;
  readonly strategyEngine?: IStrategyEngine;
  readonly channelEngine?: IChannelEngine;
  readonly scriptEngine?: IScriptEngine;
  readonly assetEngine?: IAssetEngine;
  readonly productionEngine?: IProductionEngine;
  readonly generationEngine?: IGenerationEngine;
  readonly compositionEngine?: ICompositionEngine;
  readonly renderEngine?: IRenderEngine;
  readonly qualityEngine?: IQualityEngine;
}
