import { ModelDescriptor } from "@shaily/core";

export const NvidiaModels: readonly ModelDescriptor[] = [
  {
    id: "nvidia/llama-3.1-405b-instruct",
    providerId: "nvidia",
    capabilities: {
      chat: true,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 4096,
    costMetadata: { inputCostPer1K: 0.0026, outputCostPer1K: 0.0026 },
    latencyMetadata: { averageLatencyMs: 400 },
    enabled: true,
    displayName: "Llama 3.1 405B Instruct (NVIDIA)",
    vision: false,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "nvidia/llama-3.1-70b-instruct",
    providerId: "nvidia",
    capabilities: {
      chat: true,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 4096,
    costMetadata: { inputCostPer1K: 0.0007, outputCostPer1K: 0.0007 },
    latencyMetadata: { averageLatencyMs: 150 },
    enabled: true,
    displayName: "Llama 3.1 70B Instruct (NVIDIA)",
    vision: false,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
];
