export enum SocialEventType {
  PUBLISH_STARTED = "PUBLISH_STARTED",
  PUBLISH_PROGRESS = "PUBLISH_PROGRESS",
  PUBLISH_COMPLETED = "PUBLISH_COMPLETED",
  PLATFORM_CONNECTED = "PLATFORM_CONNECTED",
  RETRY_STARTED = "RETRY_STARTED",
  ANALYTICS_INITIALIZED = "ANALYTICS_INITIALIZED"
}
