export enum AnalyticsState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  COLLECTING = "COLLECTING",
  PROCESSING = "PROCESSING",
  AGGREGATING = "AGGREGATING",
  READY = "READY",
  FAILED = "FAILED",
  STOPPED = "STOPPED"
}
