export enum AnalyticsPlatform {
  YOUTUBE = "YOUTUBE",
  INSTAGRAM = "INSTAGRAM",
  FACEBOOK = "FACEBOOK",
  X = "X",
  LINKEDIN = "LINKEDIN",
  THREADS = "THREADS",
  TIKTOK = "TIKTOK",
  PINTEREST = "PINTEREST",
  ALL = "ALL"
}
