export enum AnalyticsEventType {
  COLLECTION_STARTED = "COLLECTION_STARTED",
  COLLECTION_COMPLETED = "COLLECTION_COMPLETED",
  METRICS_UPDATED = "METRICS_UPDATED",
  TREND_DETECTED = "TREND_DETECTED",
  REPORT_GENERATED = "REPORT_GENERATED",
  SNAPSHOT_CREATED = "SNAPSHOT_CREATED"
}
