export enum MetricType {
  VIEWS = "VIEWS",
  IMPRESSIONS = "IMPRESSIONS",
  WATCH_TIME = "WATCH_TIME",
  CTR = "CTR",
  RETENTION = "RETENTION",
  LIKES = "LIKES",
  COMMENTS = "COMMENTS",
  SHARES = "SHARES",
  SUBSCRIBERS = "SUBSCRIBERS",
  FOLLOWERS = "FOLLOWERS",
  CLICKS = "CLICKS",
  ENGAGEMENT = "ENGAGEMENT"
}
