export enum AutomationEventType {
  ROUTINE_STARTED = "ROUTINE_STARTED",
  ROUTINE_COMPLETED = "ROUTINE_COMPLETED",
  TASK_STARTED = "TASK_STARTED",
  TASK_COMPLETED = "TASK_COMPLETED",
  ALERT_TRIGGERED = "ALERT_TRIGGERED",
  BACKUP_COMPLETED = "BACKUP_COMPLETED",
  STATE_CHANGED = "STATE_CHANGED",
  ERROR_OCCURRED = "ERROR_OCCURRED"
}
