export enum CleanupPolicy {
  EXPIRED_TTL = "EXPIRED_TTL",
  LOW_SCORE = "LOW_SCORE",
  DUPLICATE_ONLY = "DUPLICATE_ONLY",
  SNAPSHOTS = "SNAPSHOTS",
  FAILED_EXECUTIONS = "FAILED_EXECUTIONS",
  ORPHAN_REFERENCES = "ORPHAN_REFERENCES",
  TEMP_CACHE = "TEMP_CACHE",
  ALL = "ALL",
}
