export enum AssetType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  AUDIO = "AUDIO",
  ANIMATION = "ANIMATION",
  BACKGROUND = "BACKGROUND",
  ICON = "ICON",
  INFOGRAPHIC = "INFOGRAPHIC",
  TEXT_OVERLAY = "TEXT_OVERLAY",
}
