import { ModelDescriptor } from "@shaily/core";

export const OllamaModels: readonly ModelDescriptor[] = [
  {
    id: "llama3",
    providerId: "ollama",
    capabilities: {
      chat: true,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 8192,
    maxOutput: 2048,
    costMetadata: { inputCostPer1K: 0, outputCostPer1K: 0 },
    latencyMetadata: { averageLatencyMs: 80 },
    enabled: true,
    displayName: "Llama 3 (Ollama Local)",
    vision: false,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "mistral",
    providerId: "ollama",
    capabilities: {
      chat: true,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 8192,
    maxOutput: 2048,
    costMetadata: { inputCostPer1K: 0, outputCostPer1K: 0 },
    latencyMetadata: { averageLatencyMs: 70 },
    enabled: true,
    displayName: "Mistral (Ollama Local)",
    vision: false,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "nomic-embed-text",
    providerId: "ollama",
    capabilities: {
      chat: false,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: false,
      jsonMode: false,
      streaming: false,
    },
    contextWindow: 2048,
    maxOutput: 0,
    costMetadata: { inputCostPer1K: 0, outputCostPer1K: 0 },
    latencyMetadata: { averageLatencyMs: 20 },
    enabled: true,
    displayName: "Nomic Embed Text (Ollama Local)",
    vision: false,
    tools: false,
    streaming: false,
    embeddings: true,
    JSON: false,
  },
];
