export enum ArchiveState {
  PENDING = "PENDING",
  ARCHIVING = "ARCHIVING",
  ARCHIVED = "ARCHIVED",
  RESTORING = "RESTORING",
  RESTORED = "RESTORED",
  FAILED = "FAILED",
  DELETED = "DELETED",
}
