export enum CompressionStrategy {
  LOSSLESS = "LOSSLESS",
  SEMANTIC = "SEMANTIC",
  CONTEXT_SUMMARY = "CONTEXT_SUMMARY",
  SNAPSHOT = "SNAPSHOT",
  EMBEDDING = "EMBEDDING",
  METADATA = "METADATA",
}
