export enum GenerationMode {
  TEXT_TO_IMAGE = "TEXT_TO_IMAGE",
  IMAGE_TO_IMAGE = "IMAGE_TO_IMAGE",
  TEXT_TO_VIDEO = "TEXT_TO_VIDEO",
  IMAGE_TO_VIDEO = "IMAGE_TO_VIDEO",
  TEXT_TO_SPEECH = "TEXT_TO_SPEECH",
  SPEECH_TO_TEXT = "SPEECH_TO_TEXT",
  TEXT_TO_MUSIC = "TEXT_TO_MUSIC",
  TEXT_TO_SFX = "TEXT_TO_SFX",
  UPSCALE = "UPSCALE",
  INPAINT = "INPAINT"
}
