export enum MediaProviderState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  PROCESSING = "PROCESSING",
  STREAMING = "STREAMING",
  FAILED = "FAILED",
  STOPPED = "STOPPED"
}
