export enum MediaEventType {
  REQUEST_STARTED = "REQUEST_STARTED",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_FAILED = "REQUEST_FAILED",
  STREAM_STARTED = "STREAM_STARTED",
  STREAM_COMPLETED = "STREAM_COMPLETED",
  PROVIDER_SWITCHED = "PROVIDER_SWITCHED",
  FALLBACK_TRIGGERED = "FALLBACK_TRIGGERED",
  MEDIA_GENERATED = "MEDIA_GENERATED"
}
