export enum StabilityState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  TESTING = "TESTING",
  PROFILING = "PROFILING",
  OPTIMIZING = "OPTIMIZING",
  CERTIFYING = "CERTIFYING",
  READY = "READY",
  FAILED = "FAILED"
}
