export enum PlanStatus {
  CREATED = "CREATED",
  PLANNING = "PLANNING",
  READY = "READY",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  FAILED = "FAILED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
