export enum ContentStage {
  STORYBOARD = "STORYBOARD",
  SCENE_PLANNING = "SCENE_PLANNING",
  IMAGE_GENERATION = "IMAGE_GENERATION",
  VOICE_GENERATION = "VOICE_GENERATION",
  MUSIC_GENERATION = "MUSIC_GENERATION",
  SFX_GENERATION = "SFX_GENERATION",
  VIDEO_GENERATION = "VIDEO_GENERATION",
  COMPOSITION = "COMPOSITION",
  RENDERING = "RENDERING",
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
  PUBLISHING_PACKAGE = "PUBLISHING_PACKAGE"
}
