export enum PipelineEventType {
  PIPELINE_STARTED = "PIPELINE_STARTED",
  STAGE_STARTED = "STAGE_STARTED",
  STAGE_COMPLETED = "STAGE_COMPLETED",
  ASSET_GENERATED = "ASSET_GENERATED",
  QUALITY_FAILED = "QUALITY_FAILED",
  PIPELINE_COMPLETED = "PIPELINE_COMPLETED"
}
