export enum SchedulerEventType {
  TASK_CREATED = "TASK_CREATED",
  TASK_STARTED = "TASK_STARTED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_FAILED = "TASK_FAILED",
  TASK_RETRIED = "TASK_RETRIED",
  TASK_SKIPPED = "TASK_SKIPPED",
  QUEUE_UPDATED = "QUEUE_UPDATED",
  SCHEDULER_STARTED = "SCHEDULER_STARTED",
  SCHEDULER_STOPPED = "SCHEDULER_STOPPED",
}
