export enum TaskState {
  PENDING = "PENDING",
  QUEUED = "QUEUED",
  WAITING = "WAITING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  SKIPPED = "SKIPPED",
}
