import { ModelDescriptor } from "@shaily/core";

export const GrokModels: readonly ModelDescriptor[] = [
  {
    id: "grok-2",
    providerId: "grok",
    capabilities: {
      chat: true,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 4096,
    costMetadata: { inputCostPer1K: 0.002, outputCostPer1K: 0.01 },
    latencyMetadata: { averageLatencyMs: 250 },
    enabled: true,
    displayName: "Grok 2 (xAI)",
    vision: false,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "grok-2-vision",
    providerId: "grok",
    capabilities: {
      chat: true,
      vision: true,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 128000,
    maxOutput: 4096,
    costMetadata: { inputCostPer1K: 0.002, outputCostPer1K: 0.01 },
    latencyMetadata: { averageLatencyMs: 300 },
    enabled: true,
    displayName: "Grok 2 Vision (xAI)",
    vision: true,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
];
