export enum DecisionType {
  TOOL_SELECTION = "TOOL_SELECTION",
  WORKFLOW_SELECTION = "WORKFLOW_SELECTION",
  SKILL_SELECTION = "SKILL_SELECTION",
  PLAN_SELECTION = "PLAN_SELECTION",
  PROVIDER_SELECTION = "PROVIDER_SELECTION",
  TEAM_SELECTION = "TEAM_SELECTION",
  STRATEGY_SELECTION = "STRATEGY_SELECTION",
}
