export enum ConfigurationCapability {
  SCHEMA_VALIDATION = "SCHEMA_VALIDATION",
  RUNTIME_RELOAD = "RUNTIME_RELOAD",
  CHANGE_NOTIFICATIONS = "CHANGE_NOTIFICATIONS",
  HIERARCHICAL_SECTIONS = "HIERARCHICAL_SECTIONS",
}
