export enum ConfigurationEventType {
  CONFIG_LOADED = "CONFIG_LOADED",
  SECRET_LOADED = "SECRET_LOADED",
  VALIDATION_COMPLETED = "VALIDATION_COMPLETED",
  PROVIDER_READY = "PROVIDER_READY",
  CONFIG_UPDATED = "CONFIG_UPDATED",
  SNAPSHOT_CREATED = "SNAPSHOT_CREATED"
}
