export enum ProviderType {
  OPENAI = "OPENAI",
  GEMINI = "GEMINI",
  OPENROUTER = "OPENROUTER",
  TAVILY = "TAVILY",
  HUGGINGFACE = "HUGGINGFACE",
  YOUTUBE = "YOUTUBE",
  YOUTUBE_ANALYTICS = "YOUTUBE_ANALYTICS",
  INSTAGRAM = "INSTAGRAM",
  FACEBOOK = "FACEBOOK",
  POSTGRES = "POSTGRES",
  REDIS = "REDIS",
  QDRANT = "QDRANT",
  OLLAMA = "OLLAMA"
}
