// ─── Learning Type ───────────────────────────────────────────────────────────

export enum LearningType {
  SUCCESS_PATTERN     = "SUCCESS_PATTERN",
  FAILURE_PATTERN     = "FAILURE_PATTERN",
  PROMPT_PATTERN      = "PROMPT_PATTERN",
  WORKFLOW_PATTERN    = "WORKFLOW_PATTERN",
  DECISION_PATTERN    = "DECISION_PATTERN",
  PROVIDER_PATTERN    = "PROVIDER_PATTERN",
  QUALITY_PATTERN     = "QUALITY_PATTERN",
  AUDIENCE_PATTERN    = "AUDIENCE_PATTERN",
  PERFORMANCE_PATTERN = "PERFORMANCE_PATTERN",
}
