export enum VideoCategory {
  EDUCATION = "EDUCATION",
  ENTERTAINMENT = "ENTERTAINMENT",
  GAMING = "GAMING",
  SCIENCE = "SCIENCE",
  TECHNOLOGY = "TECHNOLOGY",
  BUSINESS = "BUSINESS",
  PEOPLE = "PEOPLE",
  OTHER = "OTHER"
}
