export enum YouTubeState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  UPLOADING = "UPLOADING",
  PROCESSING = "PROCESSING",
  PUBLISHING = "PUBLISHING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}
