export enum YouTubeEventType {
  UPLOAD_STARTED = "UPLOAD_STARTED",
  UPLOAD_PROGRESS = "UPLOAD_PROGRESS",
  UPLOAD_COMPLETED = "UPLOAD_COMPLETED",
  VIDEO_PUBLISHED = "VIDEO_PUBLISHED",
  THUMBNAIL_UPLOADED = "THUMBNAIL_UPLOADED",
  PLAYLIST_UPDATED = "PLAYLIST_UPDATED"
}
