// ─── Issue Type ───────────────────────────────────────────────────────────────

export enum IssueType {
  // Visual
  BLURRY_FRAME      = "BLURRY_FRAME",
  DUPLICATE_FRAME   = "DUPLICATE_FRAME",
  FLICKERING        = "FLICKERING",
  WRONG_ASPECT      = "WRONG_ASPECT",
  BLACK_FRAME       = "BLACK_FRAME",
  BAD_TRANSITION    = "BAD_TRANSITION",
  COLOR_MISMATCH    = "COLOR_MISMATCH",
  LOW_RESOLUTION    = "LOW_RESOLUTION",

  // Audio
  AUDIO_CLIPPING    = "AUDIO_CLIPPING",
  SILENCE           = "SILENCE",
  VOLUME_IMBALANCE  = "VOLUME_IMBALANCE",
  BACKGROUND_NOISE  = "BACKGROUND_NOISE",
  MISSING_NARRATION = "MISSING_NARRATION",
  MUSIC_TOO_LOUD    = "MUSIC_TOO_LOUD",

  // Subtitle
  SUBTITLE_OVERLAP  = "SUBTITLE_OVERLAP",
  TIMING_MISMATCH   = "TIMING_MISMATCH",
  SUBTITLE_TOO_LONG = "SUBTITLE_TOO_LONG",
  SUBTITLE_TOO_FAST = "SUBTITLE_TOO_FAST",
  SPELLING_ERROR    = "SPELLING_ERROR",

  // Brand
  COLOR_OFF_BRAND   = "COLOR_OFF_BRAND",
  FONT_MISMATCH     = "FONT_MISMATCH",
  MISSING_LOGO      = "MISSING_LOGO",
  WRONG_THUMBNAIL   = "WRONG_THUMBNAIL",

  // Content
  WEAK_HOOK         = "WEAK_HOOK",
  POOR_PACING       = "POOR_PACING",
  SCENE_TOO_LONG    = "SCENE_TOO_LONG",
  WEAK_ENDING       = "WEAK_ENDING",
  MISSING_CTA       = "MISSING_CTA",
}
