export enum DatabaseEventType {
  CONNECTED               = "CONNECTED",
  DISCONNECTED            = "DISCONNECTED",
  MIGRATION_COMPLETED     = "MIGRATION_COMPLETED",
  BACKUP_CREATED          = "BACKUP_CREATED",
  RESTORE_COMPLETED       = "RESTORE_COMPLETED",
  TRANSACTION_COMMITTED   = "TRANSACTION_COMMITTED",
  TRANSACTION_ROLLED_BACK = "TRANSACTION_ROLLED_BACK",
  CACHE_INVALIDATED       = "CACHE_INVALIDATED"
}
