export enum IntegrationState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  DISCOVERING = "DISCOVERING",
  REGISTERING = "REGISTERING",
  SYNCHRONIZING = "SYNCHRONIZING",
  READY = "READY",
  FAILED = "FAILED",
  STOPPED = "STOPPED"
}
