export enum IntegrationEventType {
  ENGINE_REGISTERED = "ENGINE_REGISTERED",
  ENGINE_CONNECTED = "ENGINE_CONNECTED",
  ENGINE_FAILED = "ENGINE_FAILED",
  DEPENDENCY_RESOLVED = "DEPENDENCY_RESOLVED",
  SYNC_COMPLETED = "SYNC_COMPLETED",
  RECOVERY_STARTED = "RECOVERY_STARTED",
  RECOVERY_COMPLETED = "RECOVERY_COMPLETED",
  SYSTEM_READY = "SYSTEM_READY"
}
