export enum AssistantState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  LISTENING = "LISTENING",
  PROCESSING = "PROCESSING",
  PLANNING = "PLANNING",
  EXECUTING = "EXECUTING",
  RESPONDING = "RESPONDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}
