export enum EntityType {
  CHANNEL = "CHANNEL",
  PROJECT = "PROJECT",
  VIDEO = "VIDEO",
  IMAGE = "IMAGE",
  SCRIPT = "SCRIPT",
  WORKSPACE = "WORKSPACE",
  PROVIDER = "PROVIDER",
  MODEL = "MODEL",
  PIPELINE = "PIPELINE",
  ENGINE = "ENGINE",
  UNKNOWN = "UNKNOWN",
}
