export enum ProviderEventType {
  REGISTERED = "REGISTERED",
  UNREGISTERED = "UNREGISTERED",
  REQUEST_STARTED = "REQUEST_STARTED",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_FAILED = "REQUEST_FAILED",
  HEALTH_CHANGED = "HEALTH_CHANGED",
  FALLBACK_TRIGGERED = "FALLBACK_TRIGGERED"
}
