export enum GatewayEventType {
  REQUEST_ROUTED    = "REQUEST_ROUTED",
  RESPONSE_RECEIVED = "RESPONSE_RECEIVED",
  PROVIDER_FAILED   = "PROVIDER_FAILED",
  RETRY_ATTEMPTED   = "RETRY_ATTEMPTED",
  CIRCUIT_OPENED    = "CIRCUIT_OPENED",
  QUOTA_EXCEEDED    = "QUOTA_EXCEEDED"
}
