export enum ProviderAdapterType {
  OPENAI      = "OPENAI",
  GEMINI      = "GEMINI",
  OPENROUTER  = "OPENROUTER",
  HUGGINGFACE = "HUGGINGFACE",
  OLLAMA      = "OLLAMA",
  TAVILY      = "TAVILY",
  YOUTUBE     = "YOUTUBE",
  INSTAGRAM   = "INSTAGRAM",
  FACEBOOK    = "FACEBOOK",
  NVIDIA      = "NVIDIA",
  GROK        = "GROK",
  GEMINI_IMAGE = "GEMINI_IMAGE",
  NVIDIA_IMAGE = "NVIDIA_IMAGE",
  OPENAI_IMAGE = "OPENAI_IMAGE"
}
