export enum AITaskType {
  CHAT = "CHAT",
  VISION = "VISION",
  EMBEDDINGS = "EMBEDDINGS",
  TOOL_CALLING = "TOOL_CALLING",
  STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT",
  JSON_MODE = "JSON_MODE",
  CLASSIFICATION = "CLASSIFICATION",
  SUMMARIZATION = "SUMMARIZATION",
  TRANSLATION = "TRANSLATION",
  CODE_GENERATION = "CODE_GENERATION",
  REASONING = "REASONING",
}
