export enum ConversationCapability {
  MULTIPLE_CONVERSATIONS = "MULTIPLE_CONVERSATIONS",
  UNLIMITED_MESSAGES = "UNLIMITED_MESSAGES",
  SESSION_GROUPING = "SESSION_GROUPING",
  ATTACHMENTS = "ATTACHMENTS",
  SEARCH = "SEARCH",
  SUMMARIES = "SUMMARIES",
  SOFT_DELETE = "SOFT_DELETE",
}
