export enum ImprovementState {
  CREATED = "CREATED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  LEARNING = "LEARNING",
  OPTIMIZING = "OPTIMIZING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  STOPPED = "STOPPED"
}
