export enum ImprovementEventType {
  LEARNING_COMPLETED = "LEARNING_COMPLETED",
  RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED",
  OPTIMIZATION_APPLIED = "OPTIMIZATION_APPLIED",
  EXPERIMENT_STARTED = "EXPERIMENT_STARTED",
  EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED",
  FEEDBACK_LOOP_CONNECTED = "FEEDBACK_LOOP_CONNECTED"
}
