export enum RecommendationType {
  SHORTEN_HOOK = "SHORTEN_HOOK",
  REDUCE_INTRO = "REDUCE_INTRO",
  SWITCH_PROVIDER = "SWITCH_PROVIDER",
  SHIFT_PUBLISHING_TIME = "SHIFT_PUBLISHING_TIME",
  INCREASE_PACING = "INCREASE_PACING",
  CHANGE_THUMBNAIL_STYLE = "CHANGE_THUMBNAIL_STYLE",
  BUDGET_CUT = "BUDGET_CUT",
  QUALITY_BOOST = "QUALITY_BOOST",
  OTHER = "OTHER"
}
