import { ModelDescriptor } from "@shaily/core";

export const GeminiVoiceModels: readonly ModelDescriptor[] = [
  {
    id: "gemini-tts-1",
    providerId: "google",
    capabilities: {
      chat: false,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: true,
      toolCalling: false,
      jsonMode: false,
      streaming: false,
    },
    contextWindow: 0,
    maxOutput: 0,
    costMetadata: { inputCostPer1K: 0.004, outputCostPer1K: 0.015 },
    latencyMetadata: { averageLatencyMs: 1500 },
    enabled: true,
    displayName: "Gemini Text-to-Speech (Google)",
    vision: false,
    tools: false,
    streaming: false,
    embeddings: false,
    JSON: false,
  },
  {
    id: "gemini-stt-1",
    providerId: "google",
    capabilities: {
      chat: false,
      vision: false,
      imageGeneration: false,
      audioInput: true,
      audioOutput: false,
      toolCalling: false,
      jsonMode: false,
      streaming: false,
    },
    contextWindow: 0,
    maxOutput: 0,
    costMetadata: { inputCostPer1K: 0.006, outputCostPer1K: 0.024 },
    latencyMetadata: { averageLatencyMs: 2000 },
    enabled: true,
    displayName: "Gemini Speech-to-Text (Google)",
    vision: false,
    tools: false,
    streaming: false,
    embeddings: false,
    JSON: false,
  }
];
