import { ModelDescriptor } from "@shaily/core";

export const GeminiModels: readonly ModelDescriptor[] = [
  {
    id: "gemini-1.5-pro",
    providerId: "google",
    capabilities: {
      chat: true,
      vision: true,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 2000000,
    maxOutput: 8192,
    costMetadata: { inputCostPer1K: 0.007, outputCostPer1K: 0.021 },
    latencyMetadata: { averageLatencyMs: 400 },
    enabled: true,
    displayName: "Gemini 1.5 Pro (Google)",
    vision: true,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "gemini-1.5-flash",
    providerId: "google",
    capabilities: {
      chat: true,
      vision: true,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: true,
      jsonMode: true,
      streaming: true,
    },
    contextWindow: 1000000,
    maxOutput: 8192,
    costMetadata: { inputCostPer1K: 0.000075, outputCostPer1K: 0.0003 },
    latencyMetadata: { averageLatencyMs: 120 },
    enabled: true,
    displayName: "Gemini 1.5 Flash (Google)",
    vision: true,
    tools: true,
    streaming: true,
    embeddings: false,
    JSON: true,
  },
  {
    id: "text-embedding-004",
    providerId: "google",
    capabilities: {
      chat: false,
      vision: false,
      imageGeneration: false,
      audioInput: false,
      audioOutput: false,
      toolCalling: false,
      jsonMode: false,
      streaming: false,
    },
    contextWindow: 2048,
    maxOutput: 0,
    costMetadata: { inputCostPer1K: 0.00002, outputCostPer1K: 0 },
    latencyMetadata: { averageLatencyMs: 60 },
    enabled: true,
    displayName: "Text Embedding 004 (Google)",
    vision: false,
    tools: false,
    streaming: false,
    embeddings: true,
    JSON: false,
  },
];
