export enum FounderEventType {
  DECISION_MADE = "DECISION_MADE",
  GOAL_COMPLETED = "GOAL_COMPLETED",
  DAILY_BRIEF_GENERATED = "DAILY_BRIEF_GENERATED",
  RECOMMENDATION_ACTIVE = "RECOMMENDATION_ACTIVE",
  COMMAND_RECEIVED = "COMMAND_RECEIVED",
  COMMAND_COMPLETED = "COMMAND_COMPLETED",
  ERROR_OCCURRED = "ERROR_OCCURRED"
}
