export enum ExecutionState {
  CREATED = "CREATED",
  READY = "READY",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  RECOVERING = "RECOVERING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  TIMEOUT = "TIMEOUT",
}
